spring.application.name=SingScapes
server.port=${SERVER_PORT:8080}
server.address=0.0.0.0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

stb.api.key=${STB_API_KEY}
lta.datamall.accountkey=${LTA_DATAMALL_KEY}
google.maps.api.key=${GOOGLE_MAPS_API_KEY}
supabase.jwt.secret=${SUPABASE_JWT_SECRET}
